Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -60,11 +60,15 @@ jobs:
           # Enable and start Apache
           echo "$SUDO_PASSWORD" | sudo systemctl enable apache2
           echo "$SUDO_PASSWORD" | sudo systemctl start apache2
-          
-      - name: Final mount check
-        run: |
-          if mountpoint -q /cvmfs/example.domain.tld; then
-            echo "✅ CVMFS Stratum0 is mounted."
-          else
-            echo "❌ Failed to mount CVMFS Stratum0." && exit 1
-          fi
+
+       - name: Final mount check
+          run: |
+            sudo cvmfs_config setup
+            sudo cvmfs_config reload
+            sudo mount -t cvmfs example.domain.tld /cvmfs/example.domain.tld || true
+
+            if mountpoint -q /cvmfs/example.domain.tld; then
+              echo "✅ CVMFS Stratum0 is mounted."
+            else
+              echo "❌ Failed to mount CVMFS Stratum0." && exit 1
+            fi
