Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -60,11 +60,11 @@ jobs:
           # Enable and start Apache
           echo "$SUDO_PASSWORD" | sudo systemctl enable apache2
           echo "$SUDO_PASSWORD" | sudo systemctl start apache2
-
+          
       - name: Final mount check
         run: |
           if mountpoint -q /cvmfs/example.domain.tld; then
-            echo "CVMFS Stratum0 is mounted."
+            echo "✅ CVMFS Stratum0 is mounted."
           else
-            echo "Failed to mount CVMFS Stratum0." && exit 1
-          fis made up of one or more jobs that can run sequentially or in parallel
+            echo "❌ Failed to mount CVMFS Stratum0." && exit 1
+          fi
